### PR TITLE
Use Github Actions instead of Travis

### PR DESCRIPTION
**Pull request by mmachatschek**
This is WIP.

As most laravel packages were already moved to Github actions, this would be a good time to follow along.

#### Pre-Merge TODOs

- [ ] Activate Github Actions for this repo
- [ ] Add Github Secrets to properly execute tests
  - [ ] MOLLIE_KEY
  - [ ] MANDATED_CUSTOMER_DIRECTDEBIT
  - [ ] MANDATED_CUSTOMER_DIRECTDEBIT_MANDATE_ID
  - [ ] MANDATE_PAYMENT_PAID_ID
  - [ ] SUBSCRIPTION_MANDATE_PAYMENT_PAID_ID
  - [ ] PAYMENT_PAID_ID
  - [ ] PAYMENT_FAILED_ID
- [x] Replace travis badge in README with a Github Actions badge
- [x] Remove .travis config

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Hi @mmachatschek ,

Thanks for contributing this. I guess you'll need some help with the open to do's?

**Comment by mmachatschek** [comment]
Hi @sandervanhooft,

actually the open TODOs can't be completed by me, as I can not setup secrets for this repo. The keys mentioned above were set on travis side, back when the tool was setup. Now we need to add the same keys in the settings of the repo https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by sandervanhooft** [comment]
That's what I figured.

@taylorotwell , can you help configure the secret keys and enable GitHub Actions?

**Comment by mmachatschek** [comment]
In case you guys want to check runs on my fork: https://github.com/mmachatschek/cashier-mollie/actions/runs/67766609

**Comment by sandervanhooft** [comment]
I've refactored the cashier tests to no longer call Mollie's API. So the environment variables can be dropped.

@mmachatschek can you give it a try?

**Comment by mmachatschek** [comment]
@sandervanhooft closing this because rebasing didnt work for me

**Pull request closed without merging**
