### PR TITLE
Add PHP 8 ci tests

### PR DESCRIPTION
**Pull request by mmachatschek**
Follow up of #275 

Blocking

- [x] https://github.com/mollie/laravel-mollie
- [x] https://github.com/dompdf/dompdf/pull/2313
- [x] dompdf 1.0 release

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Laravel-mollie now supports php8

**Comment by mmachatschek** [comment]
@sandervanhooft rebased branch to develop

**Comment by sandervanhooft** [comment]
@mmachatschek I think we can safely disable the integration tests, I only run these locally

**Comment by mmachatschek** [comment]
@sandervanhooft I'll send another PR to remove the integration Workflow

**Comment by sandervanhooft** [comment]
I've merged your PR removing the integration tests. Can you pull in the latest `develop` into this PR?

**Comment by mmachatschek** [comment]
@sandervanhooft done

**Comment by sandervanhooft** [comment]
Thanks @mmachatschek . Let's wait for the dompdf php8 compatibility to be fixed first.

**Comment by mmachatschek** [comment]
@sandervanhooft PR was merged but we still need to wait for the 1.0 release of dompdf

**Comment by sandervanhooft** [comment]
Thanks @mmachatschek

**Comment by ciungulete** [comment]
@sandervanhooft, now it's ok dompdf.

**Comment by mmachatschek** [comment]
@ciungulete we need to wait for the release so it can be installed via composer

**Comment by mmachatschek** [comment]
@sandervanhooft can you retrigger the test?

**Comment by sandervanhooft** [comment]
Done, but still some errors regarding dompdf config

**Comment by ciungulete** [comment]
@mmachatschek, need to update dompdf  to v1.0 in `composer.json`

**Comment by mmachatschek** [comment]
@ciungulete thanks for the hint :+1: 

@sandervanhooft looks good now

**Comment by sandervanhooft** [comment]
Thanks @mmachatschek !

@ciungulete can you make sure this ends up in v2 as well?

**Comment by ciungulete** [comment]
Yes, @sandervanhooft!

**Pull request merged**
