### PR TITLE
Use custom interval configuration

### PR DESCRIPTION
**Pull request by mmachatschek**

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Thanks for taking a shot at this @mmachatschek , much appreciated.

You're now essentially combining the behaviour of three Interval generators in one. I think it would be better to split them up in three simple classes, all implementing the same Interval(Generator)Contract.

Then in the plan config, you could swap the generator out depending on your use case. The current `interval` config key can be used to pass in parameter values. As you suggested, either a string or an array.

What do you think?

**Comment by mmachatschek** [comment]
@sandervanhooft sounds great! I'll update the PR and bump you as soon as you can have another look!

**Comment by mmachatschek** [comment]
@sandervanhooft the PR now contains extendable `Intervall::class`'s

**Comment by mmachatschek** [comment]
One more issue appeared upon going threw this.
What should happen when you reset the cycle? With a fixed interval now you will have problems with the first cycle as you its reset to the day of creation of the subscription.

See `Subscription::restartCycleWithModifications()`

**Comment by sandervanhooft** [comment]
`Subscription::restartCycleWithModifications()` is resetting to the start of the cycle `cycle_started_at`, not the start of the subscription `created_at`.

**Comment by hadjedjvincent** [comment]
@mmachatschek you have a typo on `IntervalConfigrationInvalidException` class name, should be `IntervalConfigurationInvalidException` 😄

**Comment by mmachatschek** [comment]
@sandervanhooft I'm closing this for now due to lack of time. If anyone else wants to pick up parts from this PR, feel free!

**Pull request closed without merging**
