### PR TITLE
Add translation option for hardcoded strings

### PR DESCRIPTION
**Pull request by lexdewilligen**
This PR adds translation files that can be used to translate hardcoded string. For example, when an order is processed, order items are filled with `description_extra_lines` containing a cycle. This cycle is currently defined in english, however, someone may want this cycle in their own language on an invoice. 

Users of this package can now publish the packages translation files using `php artisan vendor:publish --tag=cashier-translations`. This will generate all translation files in their projects resources folder (`resources\lang\vendor\cashier`). This allows a user to define the hardcoded string in their own language.

### CODE REVIEW

**Comment by lexdewilligen** [comment]
@sandervanhooft any feedback on this PR?

**Comment by Mul-tiMedia** [comment]
@lexdewilligen great! It was something which was bothering me too. Perhaps we should also format the date based on the locale/timezone from the main application in laravel. Because for example we have dutch customers. And showing the date like 2020-01-01 is really confusing.

Want me to do it?

**Comment by lexdewilligen** [comment]
@Mul-tiMedia I agree. It would be great if we could adjust the date format, but I can't immediately come up with a neat solution to solve that problem. What would you suggest?

**Comment by Mul-tiMedia** [comment]
@lexdewilligen already did some digging, we can use the `IntlDateFormatter`

```
    $dateFormat = new IntlDateFormatter(App::getLocale(), IntlDateFormatter::SHORT, IntlDateFormatter::NONE);
    dd($dateFormat->format($subscription->cycle_started_at));
```

Another option would be, to set a date format in the /config/cashier.php as a config variable.

@sandervanhooft which option would you prefer?

**Comment by Mul-tiMedia** [comment]
@lexdewilligen can you add me to your branch, so i can make the changes, and update this pull request?

**Comment by lexdewilligen** [comment]
Let's first await @sandervanhooft's response

**Comment by sandervanhooft** [comment]
May make sense to derive the locale from the billable model, so it all can be translated based on the customer? Similar to `taxPercentage()`

**Comment by lexdewilligen** [comment]
@sandervanhooft the locale is set in the Laravel project itself right? Do you want any updates to this PR?

**Comment by sandervanhooft** [comment]
@lexdewilligen looks good. We're working on v2 now (TBR 2021Q1), will include it there.

Can you add a section for the README?

**Comment by lexdewilligen** [comment]
@sandervanhooft sure!

**Comment by lexdewilligen** [comment]
@sandervanhooft all done! I guess ready to merge into the v2 branch

**Pull request closed without merging**
