### PR TITLE
added previousPlan to SubscriptionPlanSwapped Event

### PR DESCRIPTION
**Pull request by tobischulz**
I was in need to know what plan the subscription has previously before it swapped. Specially on subscriptions that swapNextCycle there is no reference when the event **SubscriptionPlanSwapped** gets called. So i just added the previous plan to the SubscriptionPlanSwapped event with a temporary variable.

This will helps if you need to do a specific task based on the previous and new plan. Maybe a "Thanks for Upgrade" or "Thanks for Downgrade" email to the customer.

If there was no previous plan the $event->previousPlan will be NULL.

_Sorry for the most changes made by PHP-CS-Fixer (PSR-2)._

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Thanks for this contribution! Could you undo the cs fixer stuff? It's hard to review it like this.

**Comment by tobischulz** [comment]
Yes, i will change that.

**Comment by tobischulz** [comment]
have removed all the cs fixer stuff.

**Comment by sandervanhooft** [comment]
Thanks @tobischulz !

**Pull request merged**
