### PR TITLE
#96 Added SubscriptionStarted Event

### PR DESCRIPTION
**Pull request by pascallieverse**
Added support for the SubscriptionCreated Event regarding issue #96

### CODE REVIEW

**Comment by sandervanhooft** [comment]
Could you rename it to `SubscriptionStarted`?

(Same as SubscriptionCanceled instead of SubscriptionDeleted)

**Comment by sandervanhooft** [comment]
Also, could you add a dispatched assertion to `FirstPaymentSubscriptionBuilderTest`?

**Comment by pascallieverse** [comment]
Thanks for the feedback @sandervanhooft, I have changed the code.

**Comment by sandervanhooft** [comment]
Tweaked the docs a bit, but this is great. Thanks @pascallieverse !

**Pull request merged**
